on:
  workflow_dispatch:
  
  
jobs: 
  run_build:
   runs-on: ubuntu-latest
   defaults: 
     run:
       working-directory: ./
   steps:
   
   - name: Check out the repository to the runner 
     uses: actions/checkout@v4
    
   - name: make script file executable 
     run: chmod +x build_kernel.sh
     
   - name: Run update
     run: sudo apt update
   - name: Run upgrade
     run: sudo apt -y upgrade
   - name: Install python etc
     run: sudo apt -y install python-is-python3 build-essential openssl pip python3-virtualenv openssl
   - name: Install git
     run: sudo apt-get -y install git-all aptitude make gcc libtinfo5
   - name: Install libssl
     run: sudo aptitude -y install libssl-dev
   - name: Run script file
     run: ./build_kernel.sh
